### ISSUE TITLE
AppVeyor is hanging everywhere but PY34

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/conda-build-all-feedstock#12] opened 2016-06-26 12:02 UTC
@pelson it seems that `conda-build-all` is suffering from the same problem as `obvious-ci`.

**Comment by pelson** [comment] 2016-06-27 09:45
Thanks @ocefpaf. Are you able to cross link so that I can see any previous discussion?

**Comment by ocefpaf** [comment] 2016-06-27 11:43
Not sure there was a discussion. See AppVeyor's logs https://ci.appveyor.com/project/conda-forge/obvious-ci-feedstock/build/1.0.5

There was a failure with `conda-build 1.20.1` in some of the matrix items and then hanging for > 1 hour
with `conda-build 1.21.0` for others. Many things have changed so it is hard to pin what is wrong.

**Comment by pelson** [comment] 2016-06-27 13:38
> Many things have changed so it is hard to pin what is wrong.

OK, thanks @ocefpaf. Raising to @conda-forge/core. I've raised it in the status issue https://github.com/conda-forge/status/issues/1. Anybody with any clues about Windows freezing at test environment linking?

**Comment by msarahan** [comment] 2016-06-27 13:47
Does this happen with conda-build 1.21.2?

I had hangs locally with the source_hg test with python > 2.7.  This was because it was trying to install hg in a python 3 environment, which is unsatisfiable because hg only supports python 2.  Rather than erroring out, it was hanging.  Maybe something like that happening here?  I kind of don't think so, because it does get past the package resolution phase.  I haven't seen any other hangs, though...

**Comment by mwcraig** [comment] 2016-06-27 14:12
I was hitting this last week on appveyor, couldn't quite reproduce locally but was hitting an issue with activate not working. It didn't raise an error, it just sat there, when it tried to `activate _test`. IIRC, conda 4.1.3 lists a broken activate on Windows as a known issue.

I'll try again to reproduce the fail I was seeing; it appeared to not occur if I wasn't building conda-build itself.

Actually, it was really strange. Just before it activated the _test environment activate.bat was overwritten, after which activate was broken.

**Comment by msarahan** [comment] 2016-06-27 14:16
The brokenness that I know of in 4.1.3 is more minor than this - just some wrong environment variables, so that activate.d scripts don't get found.  Still, could certainly be something else.

Regarding the breakage of activate, that's bad.  When any environment is activated, we try to write shortcuts to the activate scripts from the new environment that point back to the root.  This might be going wrong.  Conda 4.1.4 (when it is released) does not overwrite them if they already exist, I think, so that might fix this problem.

**Comment by mwcraig** [comment] 2016-06-27 14:21
It was a fairly convoluted set of steps to get activate to break, and the last time I tried it last week it *didn't* happen, so I didn't report it...but will double check later.

**Comment by msarahan** [comment] 2016-06-27 14:23
Ah, please report it next time.  I'd much rather know - especially coming from someone like you, who I know I can ask for more details. =)

**Comment by jakirkham** [comment] 2016-06-27 14:25
So, can someone please help me understand? Is this a problem with all feedstocks, just this feedstock, a small collection of feedstocks?

**Comment by ocefpaf** [comment] 2016-06-27 14:32
@msarahan in https://ci.appveyor.com/project/conda-forge/obvious-ci-feedstock/build/job/h8bu2ufo1sp6mf4b the problem exist. The details of the software installed are below.

Build time:

```shell
    ---------------------------|-----------------
    patch-2.5.9                |                1          56 KB  defaults
    conda-env-2.5.1            |           py27_0          63 KB  defaults
    markupsafe-0.23            |           py27_2          26 KB  defaults
    psutil-4.3.0               |           py27_0         220 KB  defaults
    pytz-2016.4                |           py27_0         171 KB  defaults
    ruamel_yaml-0.11.7         |           py27_0         189 KB  defaults
    six-1.10.0                 |           py27_0          16 KB  defaults
    clyent-1.2.2               |           py27_0          15 KB  defaults
    conda-4.1.3                |           py27_0         240 KB  defaults
    jinja2-2.8                 |           py27_1         265 KB  defaults
    python-dateutil-2.5.3      |           py27_0         236 KB  defaults
    anaconda-client-1.4.0      |           py27_0         150 KB  defaults
    conda-build-1.21.2         |           py27_0         307 KB  defaults
    obvious-ci-0.5.2.dev2      |           py27_0          55 KB  pelson
```

Test time:

```shell
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    yaml-0.1.6                 |            vc9_0          80 KB  conda-forge
    markupsafe-0.18            |           py27_0          22 KB  conda-forge
    menuinst-1.4.1             |           py27_0         102 KB  defaults
    pycosat-0.6.1              |           py27_0          41 KB  conda-forge
    pytz-2016.3                |           py27_0         165 KB  conda-forge
    pyyaml-3.11                |           py27_0         112 KB  conda-forge
    requests-2.9.2             |           py27_0         584 KB  conda-forge
    six-1.10.0                 |           py27_0          18 KB  conda-forge
    python-dateutil-2.5.2      |           py27_0         236 KB  conda-forge
    obvious-ci-0.6.1           |           py27_0          56 KB  local
    ------------------------------------------------------------
                                           Total:         1.4 MB
The following NEW packages will be INSTALLED:
    anaconda-client: 1.4.0-py27_0   defaults   
    clyent:          1.2.2-py27_0   defaults   
    conda:           4.1.3-py27_0   defaults   
    conda-build:     1.21.2-py27_0  defaults   
    conda-env:       2.5.1-py27_0   defaults   
    jinja2:          2.8-py27_0     conda-forge
    markupsafe:      0.18-py27_0    conda-forge
    menuinst:        1.4.1-py27_0   defaults   
    obvious-ci:      0.6.1-py27_0   local      
    patch:           2.5.9-1        defaults   
    pip:             8.1.2-py27_0   defaults   
    psutil:          4.3.0-py27_0   defaults   
    pycosat:         0.6.1-py27_0   conda-forge
    python:          2.7.11-4       defaults   
    python-dateutil: 2.5.2-py27_0   conda-forge
    pytz:            2016.3-py27_0  conda-forge
    pyyaml:          3.11-py27_0    conda-forge
    requests:        2.9.2-py27_0   conda-forge
    ruamel_yaml:     0.11.7-py27_0  defaults   
    setuptools:      23.0.0-py27_0  defaults   
    six:             1.10.0-py27_0  conda-forge
    vs2008_runtime:  9.00.30729.1-1 defaults   
    wheel:           0.29.0-py27_0  defaults   
    yaml:            0.1.6-vc9_0    conda-forge [vc9]
C:\conda\conda-bld\test-tmp_dir>activate _test 
```

I stopped it after 7 min as that was more than enough for `obvious-ci` in old builds.

**Comment by msarahan** [comment] 2016-06-27 14:37
I'll try to reproduce locally and debug.

For the time being, you can add --no-activate as an argument to conda-build, which should disable all of the activation stuff.

**Comment by mwcraig** [comment] 2016-06-27 14:45
My steps to reproduce were:

```

1. Grab the latest miniconda for python 2/64-bit Windows and install it. I didn't set it as my default python or add it to my path in the installer.
2. Open a cmd windows and add the two appropriate items to the `%PATH%`.
3. `conda update conda` (gets me to 4.1.2)
4. Create a silly environment: `conda create -n tst python=2`
5. Activating the environment has the desired effect; after `activate env` my path is set for the new environment.
6. `deactivate` and things are still working.
7. `conda install conda-build` (this gets me 1.21.1)
8. Activating/deactivating still works.
9. Run conda build on a recipe that gets to the test stage.
10. The build hangs, immediately before which `activate.bat` is overwritten in `Scripts` in the root environment. Contents of `activate.bat` are changed in this overwrite.
11. Activate no longer works, it just hangs...
```

**Comment by mwcraig** [comment] 2016-06-27 14:47
Except that the last time I tried it the breakage didn't occur. The recipe that did break it is at https://github.com/astropy/conda-channel-ci-extras/tree/master/conda-build.recipe

**Comment by msarahan** [comment] 2016-06-27 15:35
Thanks @ocefpaf and @mwcraig 

I have gotten this to repeat on my PC with the obvious-ci package, but not the staged-recipes example.  That's fine - one is enough.  I'll get a fix out ASAP.

**Comment by ocefpaf** [comment] 2016-06-27 15:36
> I have gotten this to repeat on my PC with the obvious-ci package, but not the staged-recipes example. 

The only other packages affected by this, that I know of, is `conda-build-all`.

**Comment by pelson** [comment] 2016-06-27 15:59
> I'll get a fix out ASAP.

Remember, this could very easily be an Obvious-CI issue. Please let me know if I can help on that side.

**Comment by msarahan** [comment] 2016-06-27 16:04
I don't really see how this could be an Obvious-CI issue - as much as I'd love to have the bug be elsewhere.  You do call the conda-build internals, so you might be missing something, but creation of the environment and subsequent activation of it both seem to be happening fine.  The thing that is getting it confused is that it is trying to install symlinks into the root environment, and for some strange reason, https://github.com/conda/conda/blob/master/conda/install.py#L577 is not triggering the way it should.

**Comment by pelson** [comment] 2016-06-27 16:10
I haven't seen the problem elsewhere, but does it relate to a test dependency upon conda-build itself?

**Comment by msarahan** [comment] 2016-06-27 16:44
This PR fixes it for me: https://github.com/conda/conda/pull/2880

**Comment by pelson** [comment] 2016-07-08 11:50
This has now been replaced with a different error (although it at least doesn't hang):

```
C:\conda\conda-bld\test-tmp_dir>call activate _test 
******  B A T C H   R E C U R S I O N  exceeds STACK limits ******
Recursion Count=699, Stack Usage=90 percent
******       B A T C H   PROCESSING IS   A B O R T E D      ******
TESTS FAILED: conda-build-all-0.13.1-py27`
```

Ref: https://ci.appveyor.com/project/conda-forge/conda-build-all-feedstock/branch/master/job/cgj4qovbgv642h1x

**Comment by msarahan** [comment] 2016-07-08 12:48
This error happens when conda overwrites the activate scripts in the root environment with redirection shortcuts (which then refer to themselves, leading to the infinite recursion).  I have struggled with why this happens, but will investigate ASAP.

**Comment by pelson** [comment] 2016-07-11 20:48
@msarahan - @ocefpaf and I just tracked down an issue on https://github.com/conda-forge/staged-recipes/pull/1014#issuecomment-231842862 which occurred because we weren't able to build for py27 and py35. Did you have any luck in tracking this down?

**Comment by msarahan** [comment] 2016-07-11 20:51
This recursion mess?  I think so - in the conda PR linked above - 3025

**Comment by jakirkham** [comment] 2016-07-11 21:15
What about using Python 3.4 in staged-recipes instead of Python 3.5? It is a bit odd, but it would workaround this issue for now.

**Comment by pelson** [comment] 2016-07-11 21:30
@msarahan - do you know if that made it into a release? It looks like not yet: 
https://github.com/conda/conda/releases

@jakirkham - yes, good idea!

**Comment by msarahan** [comment] 2016-07-11 21:38
I don't think it has made it into a release yet, sorry.

**Comment by pelson** [comment] 2016-07-11 21:45
That's OK. The py34 is an option for the time being.

**Comment by jakirkham** [comment] 2016-07-26 14:15
Trying to restart as there have been a few `conda-build` releases since.

**Comment by jakirkham** [comment] 2016-07-26 14:39
This built successfully and is now released for Pythons and architectures on Windows. Going to close this out. Thanks everyone for looking into this.

**Closed by jakirkham** 2016-07-26 14:39 UTC
